flight-booker/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'flights#index'
  resources :flights,  only: [:index, :show]
  resources :bookings, only: [:new, :create, :show]
end

flight-booker/app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departing_flights, class_name: "Flight", foreign_key: "start_airport_id"
	has_many :arriving_flights, class_name: "Flight", foreign_key: "finish_airport_id"
end

flight-booker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

flight-booker/app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :flight
	has_many :passengers

	accepts_nested_attributes_for :passengers
end

flight-booker/app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :from_airport, class_name: "Airport", foreign_key: "start_airport_id"
	belongs_to :to_airport, class_name: "Airport", foreign_key: "finish_airport_id"
	has_many :bookings
	has_many :passengers, through: :bookings

	def self.valid_flights(start, finish, date)
		return if date.nil?
		where(start_airport_id: start, finish_airport_id: finish, date: (date.to_datetime.beginning_of_day..date.to_datetime.end_of_day))
	end
end

flight-booker/app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true,  format: {with: VALID_EMAIL_REGEX }
end

flight-booker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

flight-booker/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	def new
		@booking = Booking.new
		@flight = Flight.find(params[:flight_id])
		@total_passengers = params[:passengers].to_i
		@total_passengers.times { @booking.passengers.build }
	end

	def create
		@booking = Booking.new(booking_params)
		if @booking.save
			@booking.passengers.each do |passenger|
				PassengerMailer.thank_you(passenger).deliver_now
			end
			flash[:success] = "The flight has been booked successfully!"
			redirect_to @booking
		else
			@flight = Flight.find(params[:booking][:flight_id])
			flash.now[:danger] = "Please enter a valid name/email"
			render 'new'
		end
	end

	def show
		@booking = Booking.find(params[:id])
		@flight = @booking.flight
	end

	private

		def booking_params
			params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
		end
end

flight-booker/app/controllers/flights_controller.rb
class FlightsController < ApplicationController

	def index
		@airport_options = Airport.all.map { |u| [u.name, u.id] }
		@date_options = Flight.all.map { |f| f.date.strftime('%b %d, %Y') }.uniq
		@flight_options = Flight.valid_flights(params[:start_airport], params[:end_airport], params[:date])
	end
end

flight-booker/app/helpers/application_helper.rb
module ApplicationHelper
end

flight-booker/app/helpers/bookings_helper.rb
module BookingsHelper
end

flight-booker/app/helpers/flights_helper.rb
module FlightsHelper
end

flight-booker/app/views/flights/_flights_form.html.erb
<h1>Pick Your Flight</h1>

<%= form_tag(new_booking_path, method: "get") do %>
	<%= hidden_field_tag(:passengers, params[:passengers]) %>
	<table class="table">
		<thead>
			<tr>
				<th></th>
				<th>Flight No.</th>
				<th>From</th>
				<th>To</th>
				<th>Time</th>
				<th>Duration</th>
				<th>Date</th>
			</tr>
		</thead>
		<tbody>
			<% @flight_options.each do |flight| %>
			<tr>
				<td><%= radio_button_tag(:flight_id, flight.id) %></td>
				<td><%= flight.id %></td>
				<td><%= flight.from_airport.name %></td>
				<td><%= flight.to_airport.name %></td>
				<td><%= flight.date.strftime("%T") %></td>
				<td><%= flight.duration %></td>
				<td><%= flight.date.strftime("%F") %></td>
			</tr>
			<% end %>
		</tbody>
 	</table>
 	<%= submit_tag("Choose Flight", class: 'btn btn-primary mini') %>
<% end %>

flight-booker/app/views/flights/_search_form.html.erb
<%= form_tag(flights_path, method: "get") do %>

<%= label_tag(:start_airport, "Departing Airport") %>
<%= select_tag(:start_airport, options_for_select(@airport_options), class: 'form-control') %>

<%= label_tag(:end_airport, "Arriving Airport") %>
<%= select_tag(:end_airport, options_for_select(@airport_options), class: 'form-control') %>

<%= label_tag(:passengers, "Passengers Number") %>
<%= select_tag(:passengers, options_for_select([1,2,3,4]), class: 'form-control') %>

<%= label_tag(:date, "Flight Date") %>
<%= select_tag(:date, options_for_select(@date_options), class: 'form-control') %>

<%= submit_tag("Search", class: 'btn btn-primary mini') %>

<% end %>

flight-booker/app/views/flights/index.html.erb
<h1>Search Flights</h1>
  <%= render 'search_form' %>
  <% if @flight_options %>
    <%= render 'flights_form' %>
  <% end %>

flight-booker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="row">
  		<div class="col-md-6 col-md-offset-3">
  			<% flash.each do |message_type, message| %>
        	<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      	<% end %>	
  			<div class="well well-lg">
    		<%= yield %> 
    		</div>
    	</div>
    </div>
  </body>
</html>