odin-kittens/config/routes.rb
Rails.application.routes.draw do
  
  root 'kittens#index'
  resources :kittens
end

odin-kittens/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

odin-kittens/app/models/kitten.rb
class Kitten < ApplicationRecord
	validates :name, presence: true
	validates :age, presence: true
	validates :cuteness, presence: true
	validates :softness, presence: true
end

odin-kittens/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

odin-kittens/app/controllers/kittens_controller.rb
class KittensController < ApplicationController

	def index
		@kittens = Kitten.all

		respond_to do |format|
			format.html 
			format.json { render :json => @kittens }
		end
	end

	def show
		@kitten = Kitten.find(params[:id])

		respond_to do |format|
			format.html
			format.json { render :json => @kitten }
		end
	end

		

	def new
		@kitten = Kitten.new
	end

	def create
		@kitten = Kitten.new(kitten_params)
		if @kitten.save
			flash[:success] = "Your kitten has been created!"
			redirect_to @kitten
		else
			flash.now[:danger] = "Please enter valid data"
			render 'new'
		end
	end

	def edit
		@kitten = Kitten.find(params[:id])
	end

	def update
		@kitten = Kitten.find(params[:id])
		if @kitten.update_attributes(kitten_params)
			flash[:success] = "Kitten Updated!"
			redirect_to @kitten
		else
			flash.now[:danger] = "Your data is wrong!"
			render 'edit'
		end
	end

	def destroy
		Kitten.find(params[:id]).destroy
		flash[:success] = "Kitten deleted"
		redirect_to kittens_url
	end

	private

		def kitten_params
			params.require(:kitten).permit(:name, :age, :cuteness, :softness)
		end
end

odin-kittens/app/helpers/application_helper.rb
module ApplicationHelper
end

odin-kittens/app/helpers/kittens_helper.rb
module KittensHelper
end

odin-kittens/app/views/kittens/_form.html.erb
<%= form_for(@kitten, url: yield(:action)) do |f| %>

	<%= f.label :name %><br>
	<%= f.text_field :name %><br><br>

	<%= f.label :age %><br>
	<%= f.number_field :age %><br><br>

	<%= f.label :cuteness %><br>
	<%= f.text_field :cuteness %><br><br>

	<%= f.label :softness %><br>
	<%= f.text_field :softness %><br><br>

	<%= f.submit "Create" %>

<% end %>

odin-kittens/app/views/kittens/edit.html.erb
<% provide(:action, kitten_path(@kitten)) %>
<h1>Edit Your Kitten</h1>

<%= render 'form' %>

odin-kittens/app/views/kittens/index.html.erb
<h1>Kittens List</h1>

<%= link_to "New Kitten", new_kitten_path %>
<ol>
	<% @kittens.each do |kitten| %>
	<li>	<%= kitten.name %></li>
	<%= link_to "Show", kitten_path(kitten) %>
	<%= link_to "Delete", kitten_path(kitten), method: :delete %><br><br>
	<% end %>
</ol>

odin-kittens/app/views/kittens/new.html.erb
<% provide(:action, kittens_path) %>
<h1>Create Your Kitten</h1>

<%= render 'form' %>

odin-kittens/app/views/kittens/show.html.erb
<h1><%= @kitten.name.capitalize %> Page</h1>

<ul>
	<li>Name: <%= @kitten.name %></li>
	<li>Age: <%= @kitten.age %></li>
	<li>cuteness: <%= @kitten.cuteness %></li>
	<li>Softness: <%= @kitten.softness %></li><br>
	<%= link_to "Delete", kitten_path(@kitten), method: :delete %>
</ul>