private-events/config/routes.rb
Rails.application.routes.draw do

	get '/signup',    to: 'users#new'
	post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

  root 'static_pages#home'

	resources :users,  only: [:new, :create, :show]
	resources :events, only: [:index, :new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

private-events/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

private-events/app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator, class_name: "User", foreign_key: "creator_id"
	has_many :event_setups, foreign_key: "attended_events_id"
	has_many :attendees, through: :event_setups

	scope :previous_events, -> { where("date < ?", Time.now)}
	scope :upcoming_events, -> { where("date > ?", Time.now)}
end

private-events/app/models/event_setup.rb
class EventSetup < ApplicationRecord

	belongs_to :attendee, class_name: "User", foreign_key: "attendees_id"
	belongs_to :attended_event, class_name: "Event", foreign_key: "attended_events_id"
end

private-events/app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	                  format: { with: VALID_EMAIL_REGEX },
	                  uniqueness: { case_sensitive: false }

	has_many :events, foreign_key: "creator_id"
	has_many :event_setups, foreign_key: "attendees_id"
	has_many :attended_events, through: :event_setups

	# Current User
	def current_user
		@current_user = User.find_by(id: params[:id])
	end

	# Retrieve previous events
	def previous_events
		attended_events.where("date < ?", Time.now)
		#@prev_events = current_user.attended_events.where("date < ?", Time.now)
	end

	# Retrieve upcoming events
	def upcoming_events
		attended_events.where("date > ?", Time.now)
	end
end

private-events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

private-events/app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@upco_events = Event.upcoming_events
		@prev_events = Event.previous_events
	end

	def show
		@event = Event.find(params[:id])
	end

	def new
		@event = Event.new
	end

	def create
		@user = User.find(session[:user_id])
		@event = @user.events.build(event_params)
		if @event.save
			flash[:success] = "The event has been created!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def destroy
	end

	private

		def event_params
			params.require(:event).permit(:description, :location).merge(date: Time.now)
		end
end

private-events/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user
  		log_in user
  		flash[:success] = "You have logged in as #{current_user.name}"
  		redirect_to root_path
  	else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  	log_out if logged_in?
    redirect_to root_url
  end
end

private-events/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

private-events/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Account created!"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def show
		@upco_events = current_user.upcoming_events
		@prev_events = current_user.previous_events
	end

	private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

private-events/app/helpers/application_helper.rb
module ApplicationHelper
end

private-events/app/helpers/events_helper.rb
module EventsHelper
end

private-events/app/helpers/sessions_helper.rb
module SessionsHelper

	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

private-events/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

private-events/app/helpers/users_helper.rb
module UsersHelper
end

private-events/app/views/events/index.html.erb
<h1>Upcoming Events:</h1>
<% @upco_events.reverse_each do |event| %>
	<ul>
		<li>
			<ol>
				<li>Creator: <%= event.creator.name.capitalize %></li>
				<li>Description: <%= event.description %></li>
				<li>Date: <%= event.date %></li>
				<li>Location: <%= event.location %></li>
			</ol>
		</li>
	</ul>
	<% end %>

<h1>Previous Events:</h1>
<% @prev_events.reverse_each do |event| %>
	<ul>
		<li>
			<ol>
				<li>Creator: <%= event.creator.name.capitalize %></li>
				<li>Description: <%= event.description %></li>
				<li>Date: <%= event.date %></li>
				<li>Location: <%= event.location %></li>
			</ol>
		</li>
	</ul>
	<% end %>

private-events/app/views/events/new.html.erb
<h1>New Event</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
		<%=form_for(@event, url: events_path) do |f| %>

		<%= f.label :description %>
		<%= f.text_field :description, class: 'form-control' %>

		<%= f.label :location %>
		<%= f.text_field :location, class: 'form-control' %>

		<%= f.submit "Create", class: "btn btn-primary" %>
		<% end %>
  </div>
</div>

private-events/app/views/events/show.html.erb
<h1>Event Creator: <%= @event.creator.name.capitalize %></h1>
Attendees:<br><br>
		<% @event.attendees.each do |attendee| %>
			<ul>
				<li><%= attendee.name.capitalize %></li>
			</ul>
		<% end %>

private-events/app/views/static_pages/home.html.erb
<div class="center jumbotron">
	  <h1>Welcome to Private-Events</h1>

	  <h2>
	    Sign up to participate on events and/or to create your own event and invite your friends!
	  </h2>

	  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	</div>